# Common configuration.

AllCops:
  RubyInterpreters:
    - ruby
    - macruby
    - rake
    - jruby
    - rbx
  # Include common Ruby source files.
  Include:
    - "**/*.rb"
    - "**/*.arb"
    - "**/*.axlsx"
    - "**/*.builder"
    - "**/*.fcgi"
    - "**/*.gemfile"
    - "**/*.gemspec"
    - "**/*.god"
    - "**/*.jb"
    - "**/*.jbuilder"
    - "**/*.mspec"
    - "**/*.opal"
    - "**/*.pluginspec"
    - "**/*.podspec"
    - "**/*.rabl"
    - "**/*.rake"
    - "**/*.rbuild"
    - "**/*.rbw"
    - "**/*.rbx"
    - "**/*.ru"
    - "**/*.ruby"
    - "**/*.spec"
